### ISSUE TITLE
Support alternative ABIs/calling conventions (specifically "stdcall")

### ISSUE THREAD

**Issue by AndrewGaspar** [tov/libffi-rs#16] opened 2020-10-27 02:59 UTC
A small issue with this crate is that it doesn't support any calling conventions other than the system's default ABI, even though libffi supports many different calling conventions. Unfortunately, I have a Windows API that uses the `"stdcall"` calling convention. This is more-or-less OK because most of my users are on x86-64 where "stdcall" is equivalent to "C" on x86-64, but it is different on 32-bit x86.

Supporting 32-bit Windows isn't that important to me, so this isn't a big priority, but I'd like to at least register that it's a small issue.

**Comment by timfish** [comment] 2020-10-27 10:58
Am I correct in thinking that changing all instances `extern "C"` to `extern "system"` will fix this?

**Comment by YorickPeterse** [comment] 2020-10-27 13:00
@timfish I'm not sure, but if that's the case then it seems like it would be an easy fix :smile:

**Comment by timfish** [comment] 2020-10-27 13:03
I made this change to some of my code to get callbacks working on win32 but I doubt I fully understand the implications.

Bindgen currently defaults to outputting extern "c" and I don't understand why it doesn't default to "system" 🤷‍♂️

**Comment by AndrewGaspar** [comment] 2020-10-27 14:37
The documentation says `extern "system"` is equivalent to `extern "stdcall"` on Windows: https://doc.rust-lang.org/stable/reference/items/external-blocks.html#abi

However, I don't think just changing `extern "C"` to `extern "system"` is a viable solution - it would break a bunch of code simply because function pointers don't implicitly or explicitly convert, even if they're technically the same calling convention: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6660d753598d611bad7d825d59cbe0c9

RE: bindgen. In my experience, it will often turn "stdcall" functions into `extern "C"` on x86-64, and my understanding is that's because of a limitation in libclang. Only on 32-bit x86 will it preserve the "stdcall" convention. And I'm guessing they wouldn't automatically apply the "system" convention for similar reasons - basically, libclang makes it hard to work out the programmer's intention.

**Comment by AndrewGaspar** [comment] 2020-10-27 14:41
Oh, also, it seems to me that `FFI_DEFAULT_ABI` for 32-bit x86 Windows is not equivalent to `extern "system"` or `extern "stdcall"`, it's equivalent to `extern "cdecl"` - you'd need to explicitly use `FFI_STDCALL`. https://github.com/libffi/libffi/blob/7855656148b96c7070ec362d2a73af840025a2b7/src/x86/ffitarget.h#L111

**Comment by AndrewGaspar** [comment] 2020-10-27 14:53
This is probably an existing bug in the `libffi` crate?

**Comment by timfish** [comment] 2020-10-27 16:50
> I don't think just changing extern "C" to extern "system" is a viable solution 

Yeah, you're probably right there!

I would guess all the tests are passing on `i686-pc-windows-msvc` because they're all calling back into Rust code which is compiled with the same calling conventions. My code is also compiled for `i686-pc-windows-msvc` and works on both x86 and x86-64, but again I'm only using it to wrap Rust closures which are compiled with the same calling conventions.

The only time I think you're going to have to use different calling conventions is if you use `libffi-rs` to call into external code which you haven't compiled yourself, for example Win32 APIs. In that case you can use [libffi::middle::Builder](https://docs.rs/libffi/1.0.0/libffi/middle/struct.Builder.html) to construct with a specific ABI. It's only the `high` layer of abstractions which doesn't let you set the ABI and that's because they're designed specifically to call into Rust closures.

**Comment by AndrewGaspar** [comment] 2020-10-27 17:35
Yeah, though it's a little frustrating that `libffi-sys`'s definitions for the `ffi_abi` values are only for a specific arch: https://github.com/tov/libffi-sys-rs/blob/e34d0d92efb6c23028ee5cc3d29f08c22a1827fd/src/lib.rs#L83

But I guess not a deal breaker.

**Comment by timfish** [comment] 2020-10-27 17:46
Yes, so the constants are incorrect for some platforms. This is caused by dropping the bindgen dependency and using statically generated bindings.

Could you put together a PR that uses `#[cfg(...)]` attributes to ensure that these constants are all correct for each platform and arch? 

@YorickPeterse does this sound ok to you?

**Comment by timfish** [comment] 2020-10-27 17:56
I still have no idea how the tests are passing with the incorrect `ffi_abi_FFI_DEFAULT_ABI` on some platforms 🤷‍♂️

**Comment by AndrewGaspar** [comment] 2020-10-27 18:01
> Could you put together a PR that uses #[cfg(...)] attributes to ensure that these constants are all correct for each platform and arch?

Might be able to take a look at this tonight.

**Comment by YorickPeterse** [comment] 2020-10-27 18:56
@timfish Using a `cfg` sounds the right approach for using the proper value.

**Comment by AndrewGaspar** [comment] 2020-10-28 02:45
After a bit more testing, it definitely isn't OK that `FFI_STDCALL` is being used - I stuck the call to `code_ptr` inside a loop and that causes a `STATUS_ACCESS_VIOLATION` pretty quickly. Well, these two issues are definitely related. I'll try to fix.

**Comment by AndrewGaspar** [comment] 2020-10-29 01:24
OK - it's basically ready to go.

**Comment by YorickPeterse** [comment] 2020-11-02 14:22
https://github.com/tov/libffi-rs/pull/13 has been merged.

**Comment by AndrewGaspar** [comment] 2020-11-02 21:44
Awesome - I'll try to submit a PR tonight.

**Comment by YorickPeterse** [comment] 2020-11-11 18:54
With https://github.com/tov/libffi-rs/pull/17 merged I believe this can be closed. I'll be publishing a new release of libffi-sys today.

**Closed by YorickPeterse** 2020-11-11 18:54 UTC

**Comment by YorickPeterse** [comment] 2020-11-11 19:01
This and the ARM fixes by @timfish have been released in libffi-sys-rs 1.1.0. Thanks all!
